package com.s4s.charity.voteregistrationsvc.model;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "sample")
public class PaVoters {
	
@Id
@DynamoDBHashKey(attributeName = "id")
@DynamoDBAutoGeneratedKey
private String id;
	

@DynamoDBAttribute(attributeName = "Name")
private String Name;

@DynamoDBAttribute
private String email;

@DynamoDBAttribute
private String ageRange;

@DynamoDBAttribute
private String birthDate;

@DynamoDBAttribute
private String citizen;

@DynamoDBAttribute
private String city;

@DynamoDBAttribute
private String  emailId;

@DynamoDBAttribute
private String firstName;

@DynamoDBAttribute
private String gender;

@DynamoDBAttribute
private String inputAddress;

@DynamoDBAttribute
private String inputAddress2;

@DynamoDBAttribute
private String lastName;

@DynamoDBAttribute
private String mailAddress1;

@DynamoDBAttribute
private String mailAddress2;

@DynamoDBAttribute
private String  mailCity;

@DynamoDBAttribute
private String mailZipcode;

@DynamoDBAttribute
private String middleName;

@DynamoDBAttribute
private String paDriverLicense;

@DynamoDBAttribute
private String pp;

@DynamoDBAttribute
private String ssn;

@DynamoDBAttribute
private String zipcode;
	}
